// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmxdtaxeqxougkcapyiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZteGR0YXhlcXhvdWdrY2FweWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODAzNjQsImV4cCI6MjA2NzA1NjM2NH0.tYR_HI8B-VoEtHBFBcZjbfRYF3ezfUmP49Mk3fsC5Pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});